<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check DB ' => 'Выбор базы данных ',
    'Check db at first' => 'Сначала выберите базу данных',
    'Create' => 'Создать',
    'Create Db' => 'Создать Базу данных',
    'Create Field' => 'Создать файл',
    'Create Field Group' => 'Создать файл группы',
    'Create Type' => 'Создать тип',
    'Dbs' => 'Базы данных',
    'Delete' => 'Удалить',
    'Delete db ' => 'Удалить базы данных ',
    'Edit field ' => 'Изменение файла ',
    'Edit group ' => 'Изменение группы ',
    'Edit db ' => 'Изменение имени ',
    'Edit table ' => 'Изменение таблицы ',
    'FK' => 'Внешний ключ',
    'Field Groups' => 'Поле Группы',
    'Groups' => 'Группы',
    'List view' => 'Посмотреть список',
    'Login' => 'Логин',
    'Logout ({username})' => 'Выйти ({username})',
    'Name' => 'Имя',
    'No Group' => 'Нет группы',
    'Null' => 'Пустой',
    'Owner' => 'Владелец',
    'Signed' => 'Подпись',
    'Sort' => 'Сортировка',
    'Table' => 'Таблица',
    'Tables' => 'Таблицы',
    'Title' => 'Название',
    'Type' => 'Тип',
    'Types' => 'Типы',
    'Unique' => 'Уникальный',
    'Update' => 'Обновление',
    'Update {modelClass}: ' => 'Обновление {modelClass}: ',
    'View FK ' => 'Просмотр внешнего ключа ',
    'View dataType ' => 'Просмотр датаТипа ',
    'View field ' => 'Просмотр файла ',
    'View group ' => 'Просмотр группы ',
    'View table ' => 'Просмотр таблицы ',
    'Collapsed' => 'Свернута',
    'Delete field ' => 'Удалить поле ',
];